### ISSUE TITLE
[QUESTION]: Cluster Create Task "Success" but does not create cluster

### ISSUE THREAD

**Issue by jason-technology** [dell/ansible-powerstore#27] opened 2023-05-26 18:01 UTC
Cluster Validate returns success
Cluster Create returns success after 30 seconds but no action is taken.
Cluster builds correctly via REST API call using same parameters

PowerStore is 3.2
Current SDK and Collection

Task Snippet
- name: Create Cluster
      dellemc.powerstore.cluster:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        cluster_name: "{{ cluster_name }}"
        verifycert: false
        ignore_network_warnings: true
        appliances:
          - link_local_address: "{{ link_local }}"
            name: "{{ appliance_name }}"
            drive_failure_tolerance_level: "{{ drive_failure_tolerance }}"
        dns_servers:
          - "{{ dns1 }}"
          - "{{ dns2 }}"
        ntp_servers:
          - "{{ ntp1 }}"
          - "{{ ntp2 }}"
        networks:
          - type: "Management"
            prefix_length: "{{ mgmt_ip_prefix }}"
            gateway: "{{ gateway_ip }}"
            cluster_mgmt_address: "{{ cluster_ip }}"
            addresses:
              - "{{ appliance_ip }}"
              - "{{ node_a_ip }}"
              - "{{ node_b_ip }}"
        is_http_redirect_enabled: true
        wait_for_completion: true
        state: "present"
      register: create_cluster_output
      tags:
        - create_cluster

Am I doing something incorrectly?

**Comment by Bhavneet-Sharma** [comment] 2023-10-06 06:20
Issue is a duplicate of https://github.com/dell/ansible-powerstore/issues/33.

**Closed by Bhavneet-Sharma** 2023-10-06 06:20 UTC
Labels: type/question, triage/duplicate
